apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: svr3-deployment
  namespace: ns-demo
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: svr3-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40


