apiVersion: v1
kind: Service
metadata:
  name: k8s-service-svr1
  namespace: ns-demo
  labels:
    name: k8s-service-svr1
spec:
#  type: NodePort
  ports:
  - port: 18001
    targetPort: 8001
  selector:
    name: pod-svr1
