apiVersion: v1
kind: Service
metadata:
  name: k8s-service-frontend
  namespace: ns-demo
  labels:
    name: k8s-service-frontend
spec:
  type: NodePort
  ports:
  - port: 6001 
    targetPort: 6001
    nodePort: 36001
  selector:
    name: pod-frontend
