apiVersion: v1
kind: Service
metadata:
  name: k8s-service-svr2
  namespace: ns-demo
  labels:
    name: k8s-service-svr2
spec:
#  type: NodePort
  ports:
  - port: 18002
    targetPort: 8002
  selector:
    name: pod-svr2
