apiVersion: v1
kind: Service
metadata:
  name: k8s-service-svr3
  namespace: ns-demo
  labels:
    name: k8s-service-svr3
spec:
#  type: NodePort
  ports:
  - port: 18003
    targetPort: 8003
  selector:
    name: pod-svr3
